[project]
name = "accent-call-logd-client"
version = "0.1.0"
description = "Client library for the accent-call-logd HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.12"
dependencies = [
  "requests>=2.25.1",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[dependency-groups]
dev = [
    "bandit>=1.8.3",
    "deptry>=0.23.0",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "refurb>=2.0.0",
    "ruff>=0.9.10",
    "tox>=4.24.2",
]
test = [
    "coverage[toml]>=7.6.12",
    "fastapi>=0.115.11",
    "httpx>=0.28.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "pytest-httpx>=0.35.0",
    "pytest-mock>=3.14.0",
    "pytest-recording>=0.13.2",
    "respx>=0.22.0",
    "uvicorn>=0.34.0",
]

[tool.uv]
default-groups = ["dev", "test"]

[project.entry-points."accent_call_logd_client.commands"]
agent_statistics = "accent_call_logd_client.commands.agent_statistics:AgentStatisticsCommand"
cdr = "accent_call_logd_client.commands.cdr:CDRCommand"
config = "accent_call_logd_client.commands.config:ConfigCommand"
export = "accent_call_logd_client.commands.export:ExportCommand"
queue_statistics = "accent_call_logd_client.commands.queue_statistics:QueueStatisticsCommand"
retention = "accent_call_logd_client.commands.retention:RetentionCommand"
status = "accent_call_logd_client.commands.status:StatusCommand"

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_call_logd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_call_logd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
