[project]
name = "accent-call-logd-client"
version = "0.1.0"
description = "Client library for the accent-call-logd HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "requests>=2.25.1",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points."accent_call_logd_client.commands"]
agent_statistics = "accent_call_logd_client.commands.agent_statistics:AgentStatisticsCommand"
cdr = "accent_call_logd_client.commands.cdr:CDRCommand"
config = "accent_call_logd_client.commands.config:ConfigCommand"
export = "accent_call_logd_client.commands.export:ExportCommand"
queue_statistics = "accent_call_logd_client.commands.queue_statistics:QueueStatisticsCommand"
retention = "accent_call_logd_client.commands.retention:RetentionCommand"
status = "accent_call_logd_client.commands.status:StatusCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_call_logd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_call_logd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
