[project]
name = "accent"
version = "1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "cheroot>=8.5.2",
  "flask>=1.1.2",
  "itsdangerous>=1.1.0",
  "jinja2>=2.11.3",
  "markupsafe>=1.1.1",
  "marshmallow>=3.10.0",
  "netifaces2",
  "python-consul>=1.1.0",
  "pyyaml>=6.0",
  "stevedore>=5.4.1",
  "setuptools>=75.6.0",
  "werkzeug>=1.0.1",
  "accent-lib-rest-client",
  "accent-bus",
  "accent-auth-client",
  "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "ruff>=0.9.10",
]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }
accent-bus = { workspace = true }
accent-auth-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent"]

[tool.hatch.build.targets.wheel]
include = ["accent"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
