[project]
name = "accent"
version = "1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.122"
dependencies = [
  "pydantic>=2.10.6",
  "pyyaml>=6.0",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
  "accent-bus",
  "accent-auth-client",
]

[dependency-groups]
dev = [
  "bandit>=1.8.3",
  "deptry>=0.23.0",
  "mypy>=1.15.0",
  "pytest>=8.3.5",
  "pytest-cov>=6.0.0",
  "refurb>=2.0.0",
  "ruff>=0.9.10",
  "tox>=4.24.2",
]
test = [
  "coverage[toml]>=7.6.12",
  "fastapi>=0.115.11",
  "httpx>=0.28.1",
  "pytest>=8.3.5",
  "pytest-asyncio>=0.25.3",
  "pytest-cov>=6.0.0",
  "pytest-httpx>=0.35.0",
  "pytest-mock>=3.14.0",
  "pytest-recording>=0.13.2",
  "respx>=0.22.0",
  "uvicorn>=0.34.0",
]

[tool.uv]
default-groups = ["dev", "test"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }
accent-bus = { workspace = true }
accent-auth-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent"]

[tool.hatch.build.targets.wheel]
include = ["accent"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
