[project]
name = "ari"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservice.com" }]
requires-python = ">=3.11"
dependencies = ["swaggerpy"]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
swaggerpy = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["ari"]

[tool.hatch.build.targets.wheel]
include = ["ari"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
