[tool.poetry]
name = "generate-calls"
version = "0.1.0"
description = ""
authors = ["Ryan Clark <ryanc@accentservices.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
accent-amid-client = {path = "../../library/accent-amid-client"}
accent-auth-client = {path = "../../library/accent-auth-client"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
