[project]
name = "accent-test-helpers"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "docker>=5.0.3",
  "kombu>=5.0.2",
  "requests>=2.25.1",
  "sqlalchemy[asyncio]>=2.0.0",
]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.hatch.build.targets.sdist]
include = ["accent_test_helpers"]

[tool.hatch.build.targets.wheel]
include = ["accent_test_helpers"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
