[tool.mypy]
python_version = "3.12"
exclude = ["alembic/", "tests/", "migrations/"]
ignore_missing_imports = false
warn_unused_ignores = true
warn_unused_configs = true
strict = true
warn_return_any = true
warn_unreachable = true
disallow_any_generics = true
disallow_untyped_defs = true
namespace_packages = true
cache_dir = ".mypy_cache"
sqlite_cache = true
show_error_codes = true
pretty = true

[tool.mypy-aiopika.*]
ignore_missing_imports = true
