[tool.poetry]
name = "accent-voice"
version = "0.1.0"
description = ""
authors = ["Ryan Clark <ryanc@accentservices.com>"]
repository = "https://github.com/ryanwclark1/accent-voice"
documentation = "https://ryanwclark1.github.io/accent-voice/"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[tool.poetry.group.dev.dependencies]
commitizen = "^3.10.0"
dunamai = "^1.18.1"
pre-commit = "^3.4.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.6.4"
tox = "^3.25.1"
pyupgrade = "^3.15.0"
ruff = "^0.1.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-pdf-export-plugin = "^0.5.10"
mkdocstrings = {extras = ["python"], version = "^0.20.0"}
mkdocs-material = "^9.0.14"
mkdocs-with-pdf = "^0.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py310"
line-length = 99
fix = true

[tool.ruff.lint]
select = [
    "YTT",  # flake8-2020
    "S",  # flake8-bandit
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "C4",  # flake8-comprehensions
    "T10",  # flake8-debugger
    "SIM",  # flake8-simplify
    "I",  # isort
    "C90",  # mccabe
    "E",  # pycodestyle
    "W",  # pycodestyle
    "F", # pyflakes
    "PGH",  # pygrep-hooks
    "UP",  # pyupgrade
    "RUF",  # ruff
    "TRY",  # tryceratops
    "YTT",  # flake8-2020
    "S",  # flake8-bandit
]

[tool.lint.ruff.per-file-ignores]
"tests/*" = ["S101"]
"integration_tests/*" = ["S"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["service", "library"]
