# Extend the default exclusions rather than overwriting them
extend-exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
  "alembic/",           # Exclude Alembic migrations
]

# Black-compatible settings
line-length = 88
indent-width = 4

# Target Python version
target-version = "py312"

[lint]
select = [
  "E",    # Pycodestyle
  "F",    # Pyflakes
  "B",    # Bugbear
  "I",    # isort
  "D",    # pydocstyle
  "UP",   # pyupgrade
  "SIM",  # Simplifications
  "PERF", # Performance
  "PL",   # Pylint
  "FLY",  # Flynt (string formatting)
  "PYI",  # Stub files
  "TID",  # Import tidiness
  "C4",   # Comprehensions
]
extend-select = [
  "S",   # Security
  "ANN", # Type annotations
  "PT",  # pytest
  "RET", # Return statements
  "ARG", # Arguments
  "DTZ", # Date/time
]
ignore = [
  "D100",   # Missing docstring in module
  "D211",   # No blank line before class docstring
  "D213",   # Multi-line docstring summary should be on the first line
  "COM812", # Trailing comma in multi-line collection
  "D203",   # One blank line before class docstring
]
ignore-init-module-imports = true

fixable = ["ALL"]
unfixable = [
  "F401",    # Unused imports (manual review recommended)
  "C901",    # Function complexity (needs refactoring)
  "PLR2004", # Magic numbers
]

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
docstring-code-line-length = 88
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
preview = true

[lint.per-file-ignores]
"**/tests/**/*.py" = [
  "INP001",
  "S101",
  "S105",
  "S106",
  "PLR2004",
  "SLF001",
  "ANN001",
  "ANN002",
  "ANN003",
  "ANN201",
  "ANN202",
  "RET503",
  "ARG001",
  "ARG002",
  "F401",
  "B008",
  "B017",
  "PT011",
  "PT012",
  "PT017",
  "PT022",
  "DTZ005",
  "C901",
  "PERF401",
  "FAST002",
  "TC001",
  "TC002",
  "D100",
  "D101",
]
