[project]
name = "accent-amid-client"
version = "0.1.0"
description = "Client library for the accent-amid HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "requests>=2.25.1",
  "stevedore>=5.4.1",
  "typing_extensions>=4.4.0.0",
  "accent-lib-rest-client",
]

[project.entry-points."accent_amid_client.commands"]
action = "accent_amid_client.commands.action:ActionCommand"
command = "accent_amid_client.commands.command:CommandCommand"
config = "accent_amid_client.commands.config:ConfigCommand"
status = "accent_amid_client.commands.status:StatusCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_amid_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_amid_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
