apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    isDefault: true
    basicAuth: false
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.49.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
    version: 1
    orgId: 1

  - name: Loki
    type: loki
    isDefault: false
    access: proxy
    url: http://loki-gateway:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    version: 1
    orgId: 1
