version: "3"
services:
  sync:
    image: accentcommunications/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  plugind:
    image: "accent-plugind-test"
    environment:
      - ACCENT_UUID=cd030e68-ace9-4ad4-bc4e-13c8dec67898
      - ACCENT_VERSION=17.10
    volumes:
      - "../..:/usr/src/accent-plugind"
      - "./etc/accent-plugind/conf.d/50-default.yml:/etc/accent-plugind/conf.d/50-default.yml"
      # - "${LOCAL_GIT_REPOS}/accent-bus/accent_bus:/opt/venv/lib/python3.9/site-packages/accent_bus"
      # - "${LOCAL_GIT_REPOS}/accent-lib-python/accent:/opt/venv/lib/python3.9/site-packages/accent"
      # - "${LOCAL_GIT_REPOS}/accent-market-client/accent_market_client:/opt/venv/lib/python3.9/site-packages/accent_market_client"
    ports:
      - "9503"

  market:
    image: "python:3.9-slim-bullseye"
    ports:
      - "8000"
    command: ["bash", "-c", "cd /var/www && python -m http.server"]

  rabbitmq:
    image: "rabbitmq"
    ports:
      - 5672

  auth:
    image: "accentcommunications/accent-auth-mock"
    ports:
      - "9497"
