[project]
name = "accent-lib-rest-client"
version = "0.1.0"
requires-python = ">=3.12.8"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
    "stevedore>=5.4.1",
]

[dependency-groups]
test = [
    "coverage[toml]>=7.6.12",
    "fastapi>=0.115.11",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "pytest-recording>=0.13.2",
]
