[tool.poetry]
name = "accent-lib-rest-client"
version = "0.1.0"
description = "Library for the Accent REST clients"
authors = ["Ryan Clark <ryanwclark@yahoo.com>"]
readme = "README.md"
packages = [
    {include = "accent_lib_rest_client"}
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pydantic = ">=2.0.0"
httpx = "^0.28.1"
stevedore = "^5.4.0"

[tool.poetry.group.dev.dependencies]


[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
pytest-asyncio = "^0.25.0"
pytest-recording = "^0.13.2"
coverage = {extras = ["toml"], version = "^7.6.9"}
fastapi = "^0.115.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
line-length = 99
target-version = ['py310']
include = '\.pyi?$'
preview = true
exclude = '''
/(
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff]
target-version = "py312"
line-length = 99
fix = true
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF"
]


[tool.ruff.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 9

[tool.ruff.isort]
lines-after-imports = 2

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]
"integration_tests/*" = ["S"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["service", "library"]

[tool.poetry.plugins."console_scripts"]
example = "accent_lib_rest_client.example_cmd:ExampleCommand"
