version: '3.7'
services:
  db:
    image: postgres
    ports:
     - "5432"
    environment:
     - POSTGRES_USER=asterisk
     - POSTGRES_PASSWORD=password123
     - POSTGRES_DB=asterisk
     - LC_ALL=C.UTF-8
    volumes:
      - "./contribs/docker/db/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql"
