[project]
name = "accent-dao"
version = "0.1.0"
description = "Data Access Layer"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9,<4.0"
dependencies = [
  "psycopg2>=2.8.6,<3",
  "PyYAML>=5.3.1,<6",
  "SQLAlchemy>=1.3.0, <1.4.0",
  "Unidecode>=1.2.0,<2",
  "accent",
  "sqlalchemy-utils>=0.37.2,<0.38",
]

[dependency-groups]
dev = [
  "commitizen>=3.10.0,<4",
  "dunamai>=1.18.1,<2",
  "pytest>=7.2.0,<8",
  "pytest-cov>=4.0.0,<5",
  "deptry>=0.6.4,<0.7",
  "tox>=3.25.1,<4",
  "pyhamcrest>=2.0.4,<3",
  "pytz~=2023.3.post1",
]

[tool.uv.sources]
accent = { path = "../../library/accent-lib-python" }

[tool.hatch.build.targets.sdist]
include = ["accent_dao"]

[tool.hatch.build.targets.wheel]
include = ["accent_dao"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
