[project]
name = "accent-dao"
version = "0.1.0"
description = "Data Access Layer"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.11"
dependencies = [
  "psycopg[binary,pool]",
  "sqlalchemy[asyncio]>=2.0.0",
  "sqlalchemy-utils>=0.41.1",
  "greenlet>=3.1.1",
  "unidecode>=1.3.8",
  "cachetools>=5.5.2",
  "accent",
]

[dependency-groups]
dev = [
  "bandit>=1.8.3",
  "deptry>=0.23.0",
  "mypy>=1.15.0",
  "refurb>=2.0.0",
  "ruff>=0.9.10",
  "tox>=4.24.2",
  "types-cachetools>=5.5.0.20240820",
]
test = [
  "coverage[toml]>=7.6.12",
  "pytest>=8.3.5",
  "pytest-asyncio>=0.25.3",
  "pytest-cov>=6.0.0",
  "pytest-mock>=3.14.0",
]

[tool.uv.sources]
accent = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_dao"]

[tool.hatch.build.targets.wheel]
include = ["accent_dao"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
