[project]
name = "accent-dao"
version = "0.1.0"
description = "Data Access Layer"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "psycopg[binary,pool]",
  "sqlalchemy[asyncio]>=2.0.0",
  "accent",
  "sqlalchemy-utils>=0.41.1",
  "greenlet>=3.1.1",
]

[dependency-groups]
dev = ["pytest>=8.3.5", "pyhamcrest>=2.0.4", "pytz~=2023.3.post1"]

[tool.uv.sources]
accent = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_dao"]

[tool.hatch.build.targets.wheel]
include = ["accent_dao"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
