[project]
name = "accent-dird-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.11"
dependencies = [
  "httpx>=0.28.1",
  "pydantic>=2.10.6",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points]

[dependency-groups]
dev = [
  "bandit>=1.8.3",
  "deptry>=0.23.0",
  "mypy>=1.15.0",
  "refurb>=2.0.0",
  "ruff>=0.9.10",
  "tox>=4.24.2",
]
test = [
  "coverage[toml]>=7.6.12",
  "fastapi>=0.115.11",
  "httpx>=0.28.1",
  "pytest>=8.3.5",
  "pytest-asyncio>=0.25.3",
  "pytest-cov>=6.0.0",
  "pytest-httpx>=0.35.0",
  "pytest-mock>=3.14.0",
  "pytest-recording>=0.13.2",
  "respx>=0.22.0",
  "uvicorn>=0.34.0",
]

[project.entry-points."accent_dird_client.commands"]
backends = "accent_dird_client.commands.backends:BackendsCommand"
conference_source = "accent_dird_client.commands.conference_source:Command"
config = "accent_dird_client.commands.config:ConfigCommand"
csv_source = "accent_dird_client.commands.csv_source:Command"
csv_ws_source = "accent_dird_client.commands.csv_ws_source:Command"
directories = "accent_dird_client.commands.directories:DirectoriesCommand"
displays = "accent_dird_client.commands.displays:DisplaysCommand"
graphql = "accent_dird_client.commands.graphql:GraphQLCommand"
ldap_source = "accent_dird_client.commands.ldap_source:Command"
personal = "accent_dird_client.commands.personal:PersonalCommand"
phonebook = "accent_dird_client.commands.phonebook:PhonebookCommand"
phonebook_deprecated = "accent_dird_client.commands.phonebook_deprecated:DeprecatedPhonebookCommand"
accent_source = "accent_dird_client.commands.accent_source:Command"
personal_source = "accent_dird_client.commands.personal_source:Command"
phonebook_source = "accent_dird_client.commands.phonebook_source:Command"
profiles = "accent_dird_client.commands.profiles:ProfilesCommand"
sources = "accent_dird_client.commands.sources:SourcesCommand"
status = "accent_dird_client.commands.status:StatusCommand"

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_dird_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_dird_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
