[project]
name = "accent-dird-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9,<4.0"
dependencies = [
  "stevedore>=4.0.2,<5",
  "requests>=2.25.1,<3",
  "accent-lib-rest-client",
]

[project.entry-points."accent_dird_client.commands"]
backends = "accent_dird_client.commands.backends:BackendsCommand"
conference_source = "accent_dird_client.commands.conference_source:Command"
config = "accent_dird_client.commands.config:ConfigCommand"
csv_source = "accent_dird_client.commands.csv_source:Command"
csv_ws_source = "accent_dird_client.commands.csv_ws_source:Command"
directories = "accent_dird_client.commands.directories:DirectoriesCommand"
displays = "accent_dird_client.commands.displays:DisplaysCommand"
graphql = "accent_dird_client.commands.graphql:GraphQLCommand"
ldap_source = "accent_dird_client.commands.ldap_source:Command"
personal = "accent_dird_client.commands.personal:PersonalCommand"
phonebook = "accent_dird_client.commands.phonebook:PhonebookCommand"
phonebook_deprecated = "accent_dird_client.commands.phonebook_deprecated:DeprecatedPhonebookCommand"
accent_source = "accent_dird_client.commands.accent_source:Command"
personal_source = "accent_dird_client.commands.personal_source:Command"
phonebook_source = "accent_dird_client.commands.phonebook_source:Command"
profiles = "accent_dird_client.commands.profiles:ProfilesCommand"
sources = "accent_dird_client.commands.sources:SourcesCommand"
status = "accent_dird_client.commands.status:StatusCommand"

[dependency-groups]
dev = [
  "commitizen>=3.10.0,<4",
  "dunamai>=1.18.1,<2",
  "pytest>=7.2.0,<8",
  "pytest-cov>=4.0.0,<5",
  "deptry>=0.6.4,<0.7",
  "tox>=3.25.1,<4",
]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_dird_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_dird_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
