[tool.poetry]
name = "accent-dird-client"
version = "0.1.0"
description = ""
authors = ["Ryan Clark <ryanc@accentservices.com>"]
packages = [
    {include = "accent_dird_client"}
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
stevedore = "^4.0.2"
requests = "^2.25.1"
accent-lib-rest-client = {path = "../../library/accent-lib-rest-client"}


[tool.poetry.group.dev.dependencies]
commitizen = "^3.10.0"
dunamai = "^1.18.1"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.6.4"
tox = "^3.25.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"
line-length = 99
fix = true

[tool.ruff.lint]
select = [
  "YTT",  # flake8-2020
  "S",  # flake8-bandit
  "B",  # flake8-bugbear
  "A",  # flake8-builtins
  "C4",  # flake8-comprehensions
  "T10",  # flake8-debugger
  "SIM",  # flake8-simplify
  "I",  # isort
  "C90",  # mccabe
  "E",  # pycodestyle
  "W",  # pycodestyle
  "F", # pyflakes
  "PGH",  # pygrep-hooks
  "UP",  # pyupgrade
  "RUF",  # ruff
  "TRY",  # tryceratops
]

ignore = [
  "E501",  # LineTooLong
  "E731",  # DoNotAssignLambda
  "E203",  # Whitespace before ':'
  "W503",  # Line break before binary operator
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["UPDATE"]

[tool.poetry.plugins."accent_dird_client.commands"]
backends = "accent_dird_client.commands.backends:BackendsCommand"
conference_source = "accent_dird_client.commands.conference_source:Command"
config = "accent_dird_client.commands.config:ConfigCommand"
csv_source = "accent_dird_client.commands.csv_source:Command"
csv_ws_source = "accent_dird_client.commands.csv_ws_source:Command"
directories = "accent_dird_client.commands.directories:DirectoriesCommand"
displays = "accent_dird_client.commands.displays:DisplaysCommand"
graphql = "accent_dird_client.commands.graphql:GraphQLCommand"
ldap_source = "accent_dird_client.commands.ldap_source:Command"
personal = "accent_dird_client.commands.personal:PersonalCommand"
phonebook = "accent_dird_client.commands.phonebook:PhonebookCommand"
phonebook_deprecated = "accent_dird_client.commands.phonebook_deprecated:DeprecatedPhonebookCommand"
accent_source = "accent_dird_client.commands.accent_source:Command"
personal_source = "accent_dird_client.commands.personal_source:Command"
phonebook_source = "accent_dird_client.commands.phonebook_source:Command"
profiles = "accent_dird_client.commands.profiles:ProfilesCommand"
sources = "accent_dird_client.commands.sources:SourcesCommand"
status = "accent_dird_client.commands.status:StatusCommand"
