[project]
name = "accent-agentd-client"
version = "0.1.0"
description = "Client library for the accent-agentd HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "httpx>=0.28.1",
  "pydantic>=2.10.6",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points."accent_agentd_client.commands"]
agents = "accent_agentd_client.commands.agents:AgentsCommand"
status = "accent_agentd_client.commands.status:StatusCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_agentd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_agentd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
