
[project]
name = "accent-agentd-client"
version = "0.1.0"
description = "Client library for accent-agentd"
authors = []
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "mypy>=1.0.0",
]

[build-system]
requires = ["hatchling"]


build-backend = "hatchling.build"


[tool.hatch.build]
include = [
    "src/**/*.py",
    "tests/**/*.py",
]
