[project]
name = "accent-confgend-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = ["Twisted>=21.2.0"]

[project.scripts]
accent-confgen = "accent_confgend_client.main:main"

[project.entry-points]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.hatch.build.targets.sdist]
include = ["accent_confgend_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_confgend_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
