[project]
name = "accent-plugind-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "requests>=2.25.1",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points."accent_plugind_client.commands"]
config = "accent_plugind_client.commands:ConfigCommand"
market = "accent_plugind_client.commands:MarketCommand"
plugins = "accent_plugind_client.commands:PluginCommand"
status = "accent_plugind_client.commands:StatusCheckerCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_plugind_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_plugind_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
