[project]
name = "accent-webhookd-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "requests>=2.25.1",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points."accent_webhookd_client.commands"]
config = "accent_webhookd_client.commands.config:ConfigCommand"
status = "accent_webhookd_client.commands.status:StatusCommand"
subscriptions = "accent_webhookd_client.commands.subscriptions:SubscriptionsCommand"
mobile_notifications = "accent_webhookd_client.commands.mobile_notifications:MobileNotificationCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_webhookd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_webhookd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py311"
line-length = 99
fix = true
