[project]
name = "accent-uuid"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"

[project.scripts]
accent-configure-uuid = "accent_uuid.main:main"

[project.entry-points]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.hatch.build.targets.sdist]
include = ["accent_uuid", "bin/accent-configure-uuid"]

[tool.hatch.build.targets.wheel]
include = ["accent_uuid", "bin/accent-configure-uuid"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
