services:
  sync:
    depends_on:
      - auth
      - chatd
      - amid
      - confd
      - postgres
      - rabbitmq
    environment:
      TARGETS: "amid:9491 confd:9486 auth:9497 postgres:5432 rabbitmq:5672"  # dont wait chatd

  chatd:
    image: accent-chatd-test
    volumes:
      - ./etc/accent-chatd/conf.d/20-initialization.yml:/etc/accent-chatd/conf.d/20-initialization.yml:ro
