services:
  sync:
    depends_on:
      - auth
      - chatd
      - confd
      - postgres
      - rabbitmq
      - microsoft
    environment:
      TARGETS: "chatd:9304 auth:9497 confd:9486 postgres:5432 rabbitmq:5672 microsoft:9991"

  chatd:
    volumes:
      - ./etc/accent-chatd/conf.d/60-microsoft-teams.yml:/etc/accent-chatd/conf.d/50-microsoft-teams.yml:ro
