# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/accent-agentd-cli/conf.d

auth:
  host: localhost
  port: 9497
  prefix: null
  https: false
  key_file: /var/lib/accent-auth-keys/accent-agentd-cli-key.yml

agentd:
  host: localhost
  port: 9493
  prefix: null
  https: false
