[project]
name = "accent-applicationd-client"
version = "0.0.1"
dependencies = [
    "certifi>=14.5.14",
    "future ; python_full_version < '2.8'",
    "six>=1.10",
    "python-dateutil>=2.5.3",
    "setuptools>=21.0.0",
    "urllib3>=1.15.1",
]

[tool.uv]
package = false
