[project]
name = "accent-appgateway-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "certifi>=2021.10.8",
  "python-dateutil>=2.8.1",
  "urllib3>=1.26.9",
  "six>=1.16.0",
  "aiohttp>=3.8.1",
]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
