FROM python:3.12-slim-bookworm

RUN python3 -m pip install --no-cache-dir flask
COPY ./deploy/mock/accent-sysconfd-mock.py /usr/local/bin/accent-sysconfd-mock.py

EXPOSE 8668

CMD ["/usr/local/bin/accent-sysconfd-mock.py", "8668"]
