FROM accentcommunications/accent-chatd:latest

# COPY ./service/accent-chatd/ /usr/src/accent-chatd

RUN true \
    && apt-get update -qq \
    && apt-get install -y --no-install-recommends \
        netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*