FROM accentcommunications/accent-websocketd:latest

RUN true \
    && apt-get update -qq  \
    && apt-get install -y --no-install-recommends \
        netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*