asterisk:
  system_user: asterisk
  acl:
    - 'auth.tenants.read'
    - 'confd.voicemails.*.update'
    - 'confd.voicemails.read'

accent-agentd:
  system_user: accent-agentd
  acl:
    - 'auth.tenants.read'
    - 'amid.action.QueueAdd.create'
    - 'amid.action.QueuePause.create'
    - 'amid.action.QueuePenalty.create'
    - 'amid.action.QueueRemove.create'
    - 'amid.action.UserEvent.create'
    - 'amid.action.Command.create'

accent-agentd-cli:
  system_user: root
  acl:
    - 'agentd.#'
    - 'auth.tenants.read'

accent-agid:
  system_user: accent-agid
  acl:
    - 'agentd.#'
    - 'auth.tenants.read'
    - 'auth.users.*.sessions.read'
    - 'auth.users.*.tokens.read'
    - 'calld.calls.*.record.start.update'
    - 'calld.calls.*.record.stop.update'
    - 'confd.devices.*.autoprov.read'
    - 'confd.devices.*.synchronize.read'
    - 'confd.devices.read'
    - 'confd.groups.*.read'
    - 'confd.lines.*.devices.*.update'
    - 'confd.lines.read'
    - 'confd.users.*.forwards.#'
    - 'confd.users.*.services.*.*'
    - 'dird.directories.reverse.*.*.read'

accent-auth:
  system_user: accent-auth
  acl:
    - 'auth.tenants.read'
    - 'confd.users.*.read'

accent-amid:
  system_user: accent-amid
  acl: []

accent-call-logd:
  system_user: accent-call-logd
  acl:
    - 'auth.tenants.read'
    - 'confd.contexts.read'
    - 'confd.lines.read'
    - 'confd.users.*.read'

accent-call-logd-export:
  system_user: accent-call-logd
  acl:
    - 'call-logd.exports.*.download.read'

accent-calld:
  system_user: www-data
  acl:
    - 'amid.action.Command.create'
    - 'amid.action.ConfBridgeList.create'
    - 'amid.action.ConfbridgeKick.create'
    - 'amid.action.ConfbridgeMute.create'
    - 'amid.action.ConfbridgeStartRecord.create'
    - 'amid.action.ConfbridgeStopRecord.create'
    - 'amid.action.ConfbridgeUnmute.create'
    - 'amid.action.MuteAudio.create'
    - 'amid.action.Park.create'
    - 'amid.action.Parkinglots.create'
    - 'amid.action.ParkedCalls.create'
    - 'amid.action.PlayDTMF.create'
    - 'amid.action.QueuePause.create'
    - 'amid.action.Redirect.create'
    - 'amid.action.Setvar.create'
    - 'amid.action.StopMixMonitor.create'
    - 'amid.action.MixMonitor.create'
    - 'amid.action.ShowDialplan.create'
    - 'auth.tenants.read'
    - 'auth.users.*.tokens.read'
    - 'confd.#'
    - 'phoned.endpoints.*.hold.start'
    - 'phoned.endpoints.*.hold.stop'
    - 'phoned.endpoints.*.answer'

accent-chatd:
  system_user: accent-chatd
  acl:
    - 'amid.action.CoreShowChannels.create'
    - 'amid.action.DeviceStateList.create'
    - 'auth.*.external.config.read'
    - 'auth.*.external.users.read'
    - 'auth.users.*.external.*.read'
    - 'auth.users.*.read'
    - 'auth.sessions.read'
    - 'auth.tenants.read'
    - 'auth.tokens.read'
    - 'confd.ingresses.http.read'
    - 'confd.users.read'
    - 'confd.users.*.services.dnd.*'

accent-confd:
  system_user: www-data
  acl:
    - 'auth.admin.#'
    - 'auth.tenants.read'
    - 'auth.users.#'
    - 'provd.#'

accent-dird:
  system_user: www-data
  acl:
    - 'auth.tenants.read'
    - 'auth.users.*.read'

accent-dird-conference-backend:
  system_user: www-data
  acl:
    - 'auth.tenants.read'
    - 'confd.conferences.read'

accent-dird-accent-backend:
  system_user: www-data
  acl:
    - 'auth.tenants.read'
    - 'confd.infos.read'
    - 'confd.users.read'

accent-dxtora:
  system_user: accent-dxtora
  acl:
    - 'provd.dev_mgr.dhcpinfo.create'

accent-phoned:
  system_user: www-data
  acl:
    - 'amid.action.Command.create'
    - 'amid.action.PJSIPNotify.create'
    - 'auth.tenants.read'
    - 'auth.users.*.read'
    - 'confd.extensions.features.read'
    - 'confd.users.*.read'
    - 'confd.users.*.services.dnd.update'
    - 'confd.lines.read'
    - 'confd.devices.*.read'
    - 'dird.directories.lookup.*.*.read'

accent-plugind:
  system_user: accent-plugind
  acl:
    - 'confd.infos.read'

accent-plugind-cli:
  system_user: root
  acl:
    - 'plugind.#'

accent-provd:
  system_user: accent-provd
  acl:
    - 'amid.action.PJSIPNotify.create'
    - 'auth.tenants.read'

accent-provd-cli:
  system_user: root
  acl:
    - 'provd.#'

accent-setupd:
  system_user: accent-setupd
  acl: []

accent-stat:
  system_user: root
  acl:
    - 'auth.tenants.read'
    - 'confd.queues.read'
    - 'confd.agents.read'

accent-upgrade:
  system_user: root
  acl:
    - 'amid.#'
    - 'auth.#'
    - 'confd.#'
    - 'dird.#'
    - 'plugind.#'
    - 'provd.#'
    - 'webhookd.#'

accent-webhookd:
  system_user: accent-webhookd
  acl:
    - 'auth.mobile.external.config.read'
    - 'auth.users.*.external.mobile.read'
    - 'auth.users.*.read'

accent-websocketd:
  system_user: accent-websocketd
  acl:
    - 'auth.tenants.read'

accent-wizard:
  system_user: www-data
  acl:
    - '#'