[project]
name = "accent-deployd-client"
version = "0.1.0"
description = "Client library for the accent deployd HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "stevedore>=5.4.1",
  "httpx>=0.28.1",
  "pydantic>=2.10.6",
  "accent-lib-rest-client",
]

[project.entry-points."accent_deployd_client.commands"]
config = "accent_deployd_client.commands.config:ConfigCommand"
instances = "accent_deployd_client.commands.instances:InstancesCommand"
providers = "accent_deployd_client.commands.providers:ProvidersCommand"
status = "accent_deployd_client.commands.status:StatusCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_deployd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_deployd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
