[project]
name = "accent-deployd-client"
version = "0.1.0"
description = "Client library for the accent deployd HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9,<4.0"
dependencies = [
  "stevedore>=4.0.2,<5",
  "requests>=2.25.1,<3",
  "accent-lib-rest-client",
]

[project.entry-points."accent_deployd_client.commands"]
config = "accent_deployd_client.commands.config:ConfigCommand"
instances = "accent_deployd_client.commands.instances:InstancesCommand"
providers = "accent_deployd_client.commands.providers:ProvidersCommand"
status = "accent_deployd_client.commands.status:StatusCommand"

[dependency-groups]
dev = [
  "commitizen>=3.10.0,<4",
  "dunamai>=1.18.1,<2",
  "pytest>=7.2.0,<8",
  "pytest-cov>=4.0.0,<5",
  "deptry>=0.6.4,<0.7",
  "tox>=3.25.1,<4",
]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_deployd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_deployd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
