[project]
name = "accent-auth-client"
version = "0.1.0"
description = "Client library for the accent-auth HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9,<4.0"
readme = "README.md"
dependencies = [
    "requests>=2.25.1,<3",
    "stevedore>=4.0.2,<5",
    "typing-extensions>=4.4.0.0,<5",
    "accent-lib-rest-client",
]

[project.entry-points."accent_auth_client.commands"]
admin = "accent_auth_client.commands.admin:AdminCommand"
backends = "accent_auth_client.commands.backends:BackendsCommand"
config = "accent_auth_client.commands.config:ConfigCommand"
emails = "accent_auth_client.commands.emails:EmailsCommand"
external = "accent_auth_client.commands.external:ExternalAuthCommand"
groups = "accent_auth_client.commands.groups:GroupsCommand"
idp = "accent_auth_client.commands.idp:IDPCommand"
ldap_config = "accent_auth_client.commands.ldap_config:LDAPBackendConfigCommand"
policies = "accent_auth_client.commands.policies:PoliciesCommand"
refresh_tokens = "accent_auth_client.commands.refresh_tokens:RefreshTokenCommand"
saml = "accent_auth_client.commands.saml:SAMLCommand"
saml_config = "accent_auth_client.commands.saml_config:SAMLConfigCommand"
sessions = "accent_auth_client.commands.sessions:SessionsCommand"
status = "accent_auth_client.commands.status:StatusCommand"
tenants = "accent_auth_client.commands.tenants:TenantsCommand"
token = "accent_auth_client.commands.token:TokenCommand"
users = "accent_auth_client.commands.users:UsersCommand"

[dependency-groups]
dev = [
    "commitizen>=3.10.0,<4",
    "dunamai>=1.18.1,<2",
    "pytest>=7.2.0,<8",
    "pytest-cov>=4.0.0,<5",
    "deptry>=0.6.4,<0.7",
    "tox>=3.25.1,<4",
]

[tool.uv.sources]
accent-lib-rest-client = { path = "../accent-lib-rest-client" }

[tool.hatch.build.targets.sdist]
include = ["accent_auth_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_auth_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
