[project]
name = "accent-market-client"
version = "0.1.0"
description = "Client library for the accent-market HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "requests>=2.25.1",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points."accent_market_client.commands"]
plugins = "accent_market_client.commands:PluginCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_market_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_market_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
