[project]
name = "accent-market-client"
version = "0.1.0"
description = "Client library for the accent-market HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9,<4.0"
dependencies = [
  "requests>=2.25.1,<3",
  "stevedore>=4.0.2,<5",
  "accent-lib-rest-client",
]

[project.entry-points."accent_market_client.commands"]
plugins = "accent_market_client.commands:PluginCommand"

[dependency-groups]
dev = [
  "commitizen>=3.10.0,<4",
  "dunamai>=1.18.1,<2",
  "pytest>=7.2.0,<8",
  "pytest-cov>=4.0.0,<5",
  "deptry>=0.6.4,<0.7",
  "tox>=3.25.1,<4",
]

[tool.uv.sources]
accent-lib-rest-client = { path = "../accent-lib-rest-client" }

[tool.hatch.build.targets.sdist]
include = ["accent_market_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_market_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
