version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - db
    environment:
      TARGETS: "db:5432 dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/accent-dird/conf.d/20-bus-disabled.yml:/etc/accent-dird/conf.d/20-bus-disabled.yml"
      - "./tmp/data/asset.similar_sources.test.csv:/tmp/data/test.csv"
      - "./tmp/data/asset.similar_sources.test_2.csv:/tmp/data/test_2.csv"
