version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - slapd
      - db
    environment:
      TARGETS: "slapd:389 db:5432 dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/accent-dird/conf.d/20-bus-disabled.yml:/etc/accent-dird/conf.d/20-bus-disabled.yml"
  slapd:
    image: nickstenning/slapd
    environment:
      LDAP_DOMAIN: accent-dird.accentvoice.io
      LDAP_ORGANISATION: acme
      LDAP_ROOTPASS: accentpassword
    ports:
      - "389"
