version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - america
      - europe
      - asia
      - db
    environment:
      TARGETS: "america:9486 asia:9486 europe:9486 dird:9489 auth:9497 db:5432"
  dird:
    volumes:
      - "./etc/accent-dird/conf.d/20-bus-disabled.yml:/etc/accent-dird/conf.d/20-bus-disabled.yml"
  america:
    image: python:3.9-slim-bullseye
    volumes:
      - "./confd_data/asset.accent_users_multiple_accent:/tmp"
    command: "/tmp/run_confd america"
  europe:
    image: python:3.9-slim-bullseye
    volumes:
      - "./confd_data/asset.accent_users_multiple_accent:/tmp"
    command: "/tmp/run_confd europe"
  asia:
    image: python:3.9-slim-bullseye
    volumes:
      - "./confd_data/asset.accent_users_multiple_accent:/tmp"
    command: "/tmp/run_confd asia"
