[project]
name = "accent-websocketd-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = ["websocket-client>=0.57.0"]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.hatch.build.targets.sdist]
include = ["accent_websocketd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_websocketd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
