[project]
name = "accent-websocketd-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9,<4.0"
dependencies = ["websocket-client>=0.57.0,<0.58"]

[dependency-groups]
dev = [
  "commitizen>=3.10.0,<4",
  "dunamai>=1.18.1,<2",
  "pytest>=7.2.0,<8",
  "pytest-cov>=4.0.0,<5",
  "deptry>=0.6.4,<0.7",
  "tox>=3.25.1,<4",
]

[tool.hatch.build.targets.sdist]
include = ["accent_websocketd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_websocketd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
