[project]
name = "accent-bus"
version = "0.1.0"
description = "Library for internal communication"
readme = "README.md"
requires-python = ">=3.12.8"

dependencies = [
    "amqp>=5.3.1",
    "kombu>=5.4.2",
]
