[project]
name = "accent-bus"
version = "0.1.0"
description = "Library for internal communication"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "aio-pika>=9.5.5",
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = []

[tool.hatch.build.targets.sdist]
include = ["accent_bus"]

[tool.hatch.build.targets.wheel]
include = ["accent_bus"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
