[tool.poetry]
name = "accent-bus"
version = "0.1.0"
description = "Library for internal communication"
authors = ["Ryan Clark <ryanc@accentservices.com>"]
readme = "README.md"
packages = [{ include = "accent_bus" }]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
kombu = "^5.0.2"
amqp = "^5.0.2"

[tool.poetry.group.dev.dependencies]
commitizen = "^3.10.0"
dunamai = "^1.18.1"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.6.4"
tox = "^3.25.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
