[project]
name = "accent-bus"
version = "0.1.0"
description = "Library for internal communication"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "aio-pika>=9.5.5",
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
  "bandit>=1.8.3",
  "deptry>=0.23.0",
  "mypy>=1.15.0",
  "refurb>=2.0.0",
  "ruff>=0.9.10",
  "tox>=4.24.2",
  "types-cachetools>=5.5.0.20240820",
]
test = [
  "coverage[toml]>=7.6.12",
  "pytest>=8.3.5",
  "pytest-asyncio>=0.25.3",
  "pytest-cov>=6.0.0",
  "pytest-mock>=3.14.0",
]

[tool.hatch.build.targets.sdist]
include = ["accent_bus"]

[tool.hatch.build.targets.wheel]
include = ["accent_bus"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
