[project]
name = "accent-asterisk-doc-extractor"
version = "0.1.0"
description = "Documentation extraction tool for Asterisk"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"

[project.scripts]
accent-asterisk-doc-extractor = "accent_asterisk_doc_extractor.main:main"

[project.entry-points]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.hatch.build.targets.sdist]
include = ["accent_asterisk_doc_extractor"]

[tool.hatch.build.targets.wheel]
include = ["accent_asterisk_doc_extractor"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
