[tool.poetry]
name = "accent-calld-client"
version = "0.1.0"
description = ""
authors = ["Ryan Clark <ryanc@accentservices.com>"]
packages = [
    {include = "accent_calld_client"}
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
requests = "^2.25.1"
stevedore = "^4.0.2"
accent-lib-rest-client = {path = "../accent-lib-rest-client"}

[tool.poetry.group.dev.dependencies]
commitizen = "^3.10.0"
dunamai = "^1.18.1"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.6.4"
tox = "^3.25.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"
line-length = 99
fix = true

[tool.ruff.lint]
select = [
  "YTT",  # flake8-2020
  "S",  # flake8-bandit
  "B",  # flake8-bugbear
  "A",  # flake8-builtins
  "C4",  # flake8-comprehensions
  "T10",  # flake8-debugger
  "SIM",  # flake8-simplify
  "I",  # isort
  "C90",  # mccabe
  "E",  # pycodestyle
  "W",  # pycodestyle
  "F", # pyflakes
  "PGH",  # pygrep-hooks
  "UP",  # pyupgrade
  "RUF",  # ruff
  "TRY",  # tryceratops
]

ignore = [
  "E501",  # LineTooLong
  "E731",  # DoNotAssignLambda
  "E203",  # Whitespace before ':'
  "W503",  # Line break before binary operator
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["UPDATE"]

[tool.poetry.plugins."accent_calld_client.commands"]
adhoc_conferences = "accent_calld_client.commands.adhoc_conferences:AdhocConferencesCommand"
applications = "accent_calld_client.commands.applications:ApplicationsCommand"
calls = "accent_calld_client.commands.calls:CallsCommand"
conferences = "accent_calld_client.commands.conferences:ConferencesCommand"
config = "accent_calld_client.commands.config:ConfigCommand"
faxes = "accent_calld_client.commands.faxes:FaxesCommand"
lines = "accent_calld_client.commands.lines:LinesCommand"
meetings = "accent_calld_client.commands.meetings:MeetingsCommand"
relocates = "accent_calld_client.commands.relocates:RelocatesCommand"
status = "accent_calld_client.commands.status:StatusCommand"
switchboards = "accent_calld_client.commands.switchboards:SwitchboardsCommand"
transfers = "accent_calld_client.commands.transfers:TransfersCommand"
trunks = "accent_calld_client.commands.trunks:TrunksCommand"
voicemails = "accent_calld_client.commands.voicemails:VoicemailsCommand"
