[project]
name = "accent-calld-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.11"
dependencies = [
  "httpx>=0.28.1",
  "pydantic>=2.10.6",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points."accent_calld_client.commands"]
adhoc_conferences = "accent_calld_client.commands.adhoc_conferences:AdhocConferencesCommand"
applications = "accent_calld_client.commands.applications:ApplicationsCommand"
calls = "accent_calld_client.commands.calls:CallsCommand"
conferences = "accent_calld_client.commands.conferences:ConferencesCommand"
config = "accent_calld_client.commands.config:ConfigCommand"
faxes = "accent_calld_client.commands.faxes:FaxesCommand"
lines = "accent_calld_client.commands.lines:LinesCommand"
meetings = "accent_calld_client.commands.meetings:MeetingsCommand"
relocates = "accent_calld_client.commands.relocates:RelocatesCommand"
status = "accent_calld_client.commands.status:StatusCommand"
switchboards = "accent_calld_client.commands.switchboards:SwitchboardsCommand"
transfers = "accent_calld_client.commands.transfers:TransfersCommand"
trunks = "accent_calld_client.commands.trunks:TrunksCommand"
voicemails = "accent_calld_client.commands.voicemails:VoicemailsCommand"

[dependency-groups]
dev = [
  "bandit>=1.8.3",
  "deptry>=0.23.0",
  "mypy>=1.15.0",
  "refurb>=2.0.0",
  "ruff>=0.9.10",
  "tox>=4.24.2",
]
test = [
  "coverage[toml]>=7.6.12",
  "fastapi>=0.115.11",
  "httpx>=0.28.1",
  "pytest>=8.3.5",
  "pytest-asyncio>=0.25.3",
  "pytest-cov>=6.0.0",
  "pytest-httpx>=0.35.0",
  "pytest-mock>=3.14.0",
  "pytest-recording>=0.13.2",
  "respx>=0.22.0",
  "uvicorn>=0.34.0",
]

[tool.uv]
default-groups = ["dev", "test"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_calld_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_calld_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
