[project]
name = "accent-calld-client"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "requests>=2.25.1",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points."accent_calld_client.commands"]
adhoc_conferences = "accent_calld_client.commands.adhoc_conferences:AdhocConferencesCommand"
applications = "accent_calld_client.commands.applications:ApplicationsCommand"
calls = "accent_calld_client.commands.calls:CallsCommand"
conferences = "accent_calld_client.commands.conferences:ConferencesCommand"
config = "accent_calld_client.commands.config:ConfigCommand"
faxes = "accent_calld_client.commands.faxes:FaxesCommand"
lines = "accent_calld_client.commands.lines:LinesCommand"
meetings = "accent_calld_client.commands.meetings:MeetingsCommand"
relocates = "accent_calld_client.commands.relocates:RelocatesCommand"
status = "accent_calld_client.commands.status:StatusCommand"
switchboards = "accent_calld_client.commands.switchboards:SwitchboardsCommand"
transfers = "accent_calld_client.commands.transfers:TransfersCommand"
trunks = "accent_calld_client.commands.trunks:TrunksCommand"
voicemails = "accent_calld_client.commands.voicemails:VoicemailsCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_calld_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_calld_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
