[project]
name = "swaggerpy"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservice.com" }]
requires-python = ">=3.9"
dependencies = ["requests>=2.25.1", "aiohttp>=3.7.4", "websocket-client>=1.6.4"]

[project.scripts]
swagger-codegen = "swaggerpy.codegen:main"

[project.entry-points]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.hatch.build.targets.sdist]
include = ["swaggerpy"]

[tool.hatch.build.targets.wheel]
include = ["swaggerpy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
