[project]
name = "swaggerpy"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservice.com" }]
requires-python = ">=3.9,<4.0"
dependencies = [
  "requests>=2.25.1,<3",
  "aiohttp>=3.7.4,<4",
  "websocket-client>=1.6.4,<2",
]

[project.scripts]
swagger-codegen = "swaggerpy.codegen:main"

[project.entry-points]

[dependency-groups]
dev = [
  "commitizen>=3.10.0,<4",
  "dunamai>=1.18.1,<2",
  "pytest>=7.2.0,<8",
  "pytest-cov>=4.0.0,<5",
  "deptry>=0.6.4,<0.7",
  "tox>=3.25.1,<4",
]

[tool.hatch.build.targets.sdist]
include = ["swaggerpy"]

[tool.hatch.build.targets.wheel]
include = ["swaggerpy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
