[project]
name = "accent-chatd-client"
version = "0.1.0"
description = "Client library for the accent-chatd HTTP interface"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.11"
dependencies = [
  "httpx>=0.28.1",
  "pydantic>=2.10.6",
  "stevedore>=5.4.1",
  "accent-lib-rest-client",
]

[project.entry-points."accent_chatd_client.commands"]
config = "accent_chatd_client.commands.config:ConfigCommand"
rooms = "accent_chatd_client.commands.rooms:RoomCommand"
status = "accent_chatd_client.commands.status:StatusCommand"
user_presences = "accent_chatd_client.commands.user_presences:UserPresenceCommand"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_chatd_client"]

[tool.hatch.build.targets.wheel]
include = ["accent_chatd_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
