FROM accentcommunications/accent-chatd

ENV PYTHONDONTWRITEBYTECODE='true'

COPY . /usr/src/accent-chatd

WORKDIR /usr/src/accent-chatd
RUN python3 -m pip install -e . coverage[toml]
CMD ["coverage", "run", "--data-file", "/tmp/coverage", "/opt/venv/bin/accent-chatd"]
