[tool.poetry]
name = "accent-webhookd"
version = "0.1.0"
description = ""
authors = ["Ryan Clark <ryanc@accentservices.com>"]
packages = [
    {include = "accent_webhookd"}
]
include = [
    "accent_webhookd/plugins/*/api.yml"
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
alembic = "^1.13.0"
celery = "^5.0.0"
cheroot = "^8.5.2"
cryptography = "^3.3.2"
flask = "^1.1.2"
Flask-Cors = "^3.0.9"
Flask-RESTful = "^0.3.8"
google-auth = "^1.5.1"
h2 = "^4.0.0"
httpx = "^0.16.1"
itsdangerous = "^1.1.0"
Jinja2 = "^2.11.3"
jsonpatch = "^1.25"
kombu = "^5.0.2"
markupsafe = "^1.1.1"
marshmallow = "^3.10.0"
netifaces = "^0.10.9"
psycopg2 = "^2.8.6"
pyfcm = "^1.4.7"
python-consul = "^1.1.0"
PyYAML = "^5.3.1"
requests = "^2.25.1"
setproctitle = "^1.2.1"
SQLAlchemy = ">=1.3.0, <1.4.0"
SQLAlchemy-Utils = "^0.37.2"
stevedore = "^4.0.2"
urllib3 = "^1.26.5"
werkzeug = "^1.0.1"
accent = {path = "../../library/accent-lib-python"}
accent-auth-client = {path = "../../library/accent-auth-client"}
accent-bus = {path = "../../library/accent-bus"}
accent-lib-rest-client = {path = "../../library/accent-lib-rest-client"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.6.4"
pre-commit = "^2.20.0"
tox = "^3.25.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"
line-length = 99
fix = true

[tool.ruff.lint]
select = [
  "YTT",  # flake8-2020
  "S",  # flake8-bandit
  "B",  # flake8-bugbear
  "A",  # flake8-builtins
  "C4",  # flake8-comprehensions
  "T10",  # flake8-debugger
  "SIM",  # flake8-simplify
  "I",  # isort
  "C90",  # mccabe
  "E",  # pycodestyle
  "W",  # pycodestyle
  "F", # pyflakes
  "PGH",  # pygrep-hooks
  "UP",  # pyupgrade
  "RUF",  # ruff
  "TRY",  # tryceratops
]

ignore = [
  "E501",  # LineTooLong
  "E731",  # DoNotAssignLambda
  "E203",  # Whitespace before ':'
  "W503",  # Line break before binary operator
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["accent_webhookd"]

[tool.poetry.plugins."console_scripts"]
accent-webhookd = "accent_webhookd.bin.daemon:main"
accent-webhookd-init-db = "accent_webhookd.bin.init_db:main"
accent-webhookd-init-amqp = "accent_webhookd.bin.init_amqp:main"

[tool.poetry.plugins."accent_webhookd.plugins"]
api = "accent_webhookd.plugins.api.plugin:Plugin"
config = "accent_webhookd.plugins.config.plugin:Plugin"
mobile = "accent_webhookd.plugins.mobile.plugin:Plugin"
status = "accent_webhookd.plugins.status.plugin:Plugin"
subscriptions = "accent_webhookd.plugins.subscription.plugin:Plugin"
services = "accent_webhookd.plugins.services.plugin:Plugin"

[tool.poetry.plugins."accent_webhookd.services"]
http = "accent_webhookd.services.http.plugin:Service"
mobile = "accent_webhookd.services.mobile.plugin:Service"

[tool.poetry.plugins."accent_purge_db.purgers"]
webhookd-logs = "accent_webhookd.database.purger:SubscriptionLogsPurger"
