[project]
name = "accent-auth-keys"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "cliff>=3.10.1",
  "pyyaml>=6.0",
  "accent-lib-rest-client",
  "accent",
  "accent-auth-client",
  "accent-auth-cli",
]

[project.scripts]
accent-auth-keys = "accent_auth_keys.main:main"

[project.entry-points."accent_auth_keys.commands"]
service_update = "accent_auth_keys.commands.service:ServiceUpdate"
service_clean = "accent_auth_keys.commands.service:ServiceClean"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent-lib-rest-client = { workspace = true }
accent = { workspace = true }
accent-auth-client = { workspace = true }
accent-auth-cli = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_auth_keys"]

[tool.hatch.build.targets.wheel]
include = ["accent_auth_keys"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
