[project]
name = "accent-config"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9,<4.0"
dependencies = [
  "Jinja2>=2.11.3,<3",
  "netaddr>=0.8.0,<0.9",
  "netifaces>=0.10.9,<0.11",
  "PyYAML>=5.3.1,<6",
  "SQLAlchemy>=1.3.0, <1.4.0",
  "accent",
  "accent-dao",
]

[dependency-groups]
dev = [
  "commitizen>=3.10.0,<4",
  "dunamai>=1.18.1,<2",
  "pytest>=7.2.0,<8",
  "pytest-cov>=4.0.0,<5",
  "deptry>=0.6.4,<0.7",
  "tox>=3.25.1,<4",
]

[tool.uv]
package = false

[tool.uv.sources]
accent = { path = "../../library/accent-lib-python" }
accent-dao = { path = "../../library/accent-dao" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
