[project]
name = "accent-config"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.11"
dependencies = [
  "Jinja2>=3.1.6",
  "netaddr>=0.8.0",
  "netifaces2",
  "pyyaml>=6.0",
  "sqlalchemy[asyncio]>=2.0.0",
  "accent",
  "accent-dao",
]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv]
package = false

[tool.uv.sources]
accent = { workspace = true }
accent-dao = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
