version: '3'
services:
  sync:
    depends_on:
      - auth
      - call-logd
      - cel-postgres
      - confd
      - postgres
    environment:
      TARGETS: "cel-postgres:5432 postgres:5432 call-logd:9298 confd:9486 auth:9497"
