[project]
name = "accent-websocketd"
version = "0.1.0"
description = ""
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "aioamqp>=0.14.0",
  "pyyaml>=6.0",
  "requests>=2.25.1",
  "setproctitle>=1.2.1",
  "stevedore>=5.4.1",
  "websockets>=8.1",
  "accent",
  "accent-lib-rest-client",
  "accent-auth-client",
]

[project.scripts]
accent-websocketd = "accent_websocketd.main:main"
accent-websocketd-wait-online = "accent_websocketd.wait_online:main"

[project.entry-points]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.uv.sources]
accent = { workspace = true }
accent-lib-rest-client = { workspace = true }
accent-auth-client = { workspace = true }

[tool.hatch.build.targets.sdist]
include = ["accent_websocketd"]

[tool.hatch.build.targets.wheel]
include = ["accent_websocketd"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

