[tool.poetry]
name = "setup2poetry"
version = "0.1.1"
description = "Tool to convert setup.py to poetry pyproject.toml"
authors = ["Matt Magin <matt.magin@cmv.com.au>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"

[tool.poetry.group.dev.dependencies]
commitizen = "^3.10.0"
dunamai = "^1.18.1"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.6.4"
tox = "^3.25.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
setup2poetry = 'setup2poetry.cli:main'
