[project]
name = "accent-fetchfw"
version = "0.1.0"
description = "Fetch"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = [
  "progressbar2>=4.0.0",
  "pydantic>=2.10.6",
]

[project.scripts]
accent-fetchfw = "accent_fetchfw.main:main"

[project.entry-points]

[dependency-groups]
dev = [
  "bandit>=1.8.3",
  "deptry>=0.23.0",
  "mypy>=1.15.0",
  "pytest>=8.3.5",
  "pytest-cov>=6.0.0",
  "refurb>=2.0.0",
  "ruff>=0.9.10",
  "tox>=4.24.2",
]
test = [
  "coverage[toml]>=7.6.12",
  "pytest>=8.3.5",
  "pytest-asyncio>=0.25.3",
  "pytest-cov>=6.0.0",
  "pytest-recording>=0.13.2",
]

[tool.uv]
default-groups = ["dev", "test"]

[tool.hatch.build.targets.sdist]
include = ["accent_fetchfw"]

[tool.hatch.build.targets.wheel]
include = ["accent_fetchfw"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
