[project]
name = "accent-fetchfw"
version = "0.1.0"
description = "Fetch"
authors = [{ name = "Ryan Clark", email = "ryanc@accentservices.com" }]
requires-python = ">=3.9"
dependencies = ["progressbar2>=4.0.0"]

[project.scripts]
accent-fetchfw = "accent_fetchfw.main:main"

[project.entry-points]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.hatch.build.targets.sdist]
include = ["accent_fetchfw"]

[tool.hatch.build.targets.wheel]
include = ["accent_fetchfw"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
